import Image from "next/image";

// Мета данные можно писать отдельно для каждойц страницы
// export const metadata = {
//   title: "next-itwebs",
//   description: "Generated by create next app",
// };

const AboutPage = () => {
  return (
    <section className="content">
        <h2 className="section-title">About</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit quibusdam distinctio eaque, maxime veniam est exercitationem minus mollitia nulla ullam!</p>
        <Image src="/les.jpg" alt="Les" width="500" height="300" priority />
    </section>
  );
};

export default AboutPage;